FROM alpine:latest

# Maintainer
LABEL maintainer="Ron Compos <rcompos@gmail.com>"

# Install dependencies
RUN apk add fortune

# Copy alternate fortunes
COPY cowsaid /usr/bin
COPY fortunes-alt /usr/share/fortunes-alt

# Generate fortune dat files
RUN cd /usr/share/fortunes-alt; for f in `find . -type d | grep -v '^.$'`; do echo $f; strfile $f/$f $f/$f.dat; done

# Expose port 80
EXPOSE 80

# Run
ENTRYPOINT ["/usr/bin/cowsaid"]

