FROM alpine:latest

# Maintainer
LABEL maintainer="Ron Compos <rcompos@gmail.com>"

# Install dependencies
RUN apk add fortune

#ADD src /src

ADD caas /

# Expose port 80
EXPOSE 80

# Run
ENTRYPOINT ["/caas"]

