FROM scratch

# Maintainer
LABEL maintainer="Ron Compos <rcompos@gmail.com>"

# Copy executable
COPY caas /

# Copy alternate fortunes
COPY fortunes-caas /usr/share/fortunes-caas

# Generate fortune dat files
RUN cd /usr/share/fortunes-caas; for f in `find . -type d | grep -v '^.$'`; do echo $f; strfile $f/$f $f/$f.dat; done

# Expose port
EXPOSE 80

# Run
ENTRYPOINT ["/caas"]

