FROM scratch

# Maintainer
LABEL maintainer="Ron Compos <rcompos@gmail.com>"

# Copy executable
COPY cowsayer /

# Copy alternate fortunes
COPY fortunes-alt /usr/share/fortunes-alt

# Generate fortune dat files
RUN cd /usr/share/fortunes-alt; for f in `find . -type d | grep -v '^.$'`; do echo $f; strfile $f/$f $f/$f.dat; done

# Expose port
EXPOSE 80

# Run
ENTRYPOINT ["/cowsayer"]

