FROM scratch

# Maintainer
LABEL maintainer="Ron Compos <rcompos@gmail.com>"

# Copy alternate fortunes
COPY fortunes-caas /usr/share/

ADD caas /

# Expose port 8080
EXPOSE 8080

# Run
ENTRYPOINT ["/caas"]

