FROM alpine:latest

# Maintainer
LABEL maintainer="Ron Compos <rcompos@gmail.com>"

# Install dependencies
RUN apk add fortune

# Copy alternate fortunes
COPY fortunes-caas /usr/share/

# Expose port 80
EXPOSE 80

# Run
ENTRYPOINT ["/caas"]

